name: Lint Commit Messages
on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main, preproduccion, test, dev]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      ##########################
      # Checkout Commits #
      ##########################
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #####################
      # Run search secret #
      #####################
      - name: Search secret
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master
      #####################
      # Merge Next Branch #
      #####################
      - uses: actions/checkout@master

      - name: Merge dev -> test
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: test
          github_token: ${{ github.token }}

      - name: Merge test -> preproduccion
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: test
          target_branch: preproduccion
          github_token: ${{ github.token }}
          
      - name: Merge produccion -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: preproduccion
          target_branch: main
          github_token: ${{ github.token }}
      
