name: Lint Commit Messages
on: 
  pull_request:
    branches:
      - main
      - preproduccion
      - test
      - dev
      - feature/*

jobs:
  commitlint:
    name: Lint Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  superlint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  secret:
    name: Lint Secret
    runs-on: ubuntu-latest
    needs: superlint
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master