name: Branchyng Strategy
on: 
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev
      - feat/*
      - fix/*

jobs:
  commitlint:
    name: Lint Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  superlint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  secret:
    name: Lint Secret
    runs-on: ubuntu-latest
    needs: superlint
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master

  pullrequest:
    name: Pull Request Feat
    needs: secret
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Auto Pull Request
          title: 'Feat: PR to feature'
          body: Auto-created Pull Request
          branch: ${{ github.ref }} # The branch where you commit
          base: test # Don't forget to specify the right base branch here