name: Branchyng Strategy
on: 
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev
      - feat/*
      - fix/*

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: 
          curl --request POST \
          --url https://github.com/bgarrido2314/branching.git
          --header "Accept token ${GITHUB-TOKEN}"

          